baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Megakit"
pagination.pagerSize = 20
pagination.path = "/"
summaryLength = 10

[taxonomies]
category = "categories"

[permalinks]
posts = ":section/:year/:month/:day/:title/"

[markup.goldmark.renderer]
unsafe = true

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'